name: Release tagged build

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  release-tags:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/release-tags.yml@master
    secrets:
      MAVEN_USER: ${{ github.actor }}
      MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
